CREATE DATABASE quanlykho
GO
USE quanlykho
GO

CREATE TABLE KHO
(
	MAKHO VARCHAR(8) PRIMARY KEY,
	TENKHO NVARCHAR(100)
)
GO
CREATE TABLE PHIEUNHAP
(
	SOPHIEU VARCHAR(8) PRIMARY KEY,
	NGAYLAP DATETIME,
	MAKHO VARCHAR(8) REFERENCES KHO(MAKHO) ON DELETE CASCADE
)
GO
CREATE TABLE VATTU
(
	MAVT VARCHAR(8) PRIMARY KEY,
	TENVT NVARCHAR(100),
	XUATXU NVARCHAR(100)
)
GO
CREATE TABLE CHITIETPHIEUNHAP
(
	SOPHIEU VARCHAR(8) REFERENCES PHIEUNHAP(SOPHIEU) ON DELETE CASCADE,
	MAVT VARCHAR(8) REFERENCES VATTU(MAVT) ON DELETE CASCADE,
	PRIMARY KEY(MAVT,SOPHIEU),
	DONVITINH NVARCHAR(15),
	SOLUONG INT
)
GO
CREATE TABLE PHIEUXUAT
(
	MAPHIEU VARCHAR(8) PRIMARY KEY,
	NGAYXUAT DATE,
	MAKHO VARCHAR(8) REFERENCES KHO(MAKHO) ON DELETE CASCADE
)
GO
CREATE TABLE CHITIETPHIEUXUAT
(
	MAPHIEU VARCHAR(8) REFERENCES PHIEUXUAT(MAPHIEU) ON DELETE CASCADE,
	MAVT VARCHAR(8) REFERENCES VATTU(MAVT) ON DELETE CASCADE,
	PRIMARY KEY(MAVT,MAPHIEU),
	DONVITINH NVARCHAR(15),
	SOLUONG INT
)
GO
CREATE TABLE DANGNHAP
(
	TaiKhoan NVARCHAR(30),
	MatKhau VARCHAR(30)
)
GO
INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
VALUES  ( N'admin','123456'),
		( N'user1','123456')
GO
--Proc Dang Nhap
CREATE PROC DangKy(@Taikhoan NVARCHAR(30),@Matkhau NVARCHAR(30))
AS
	BEGIN
	INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
	VALUES  ( @Taikhoan, @Matkhau )
END
GO

CREATE PROC dbo.KiemTraDN(@Username VARCHAR(50),@Pass varchar(50)) AS 
BEGIN
	SELECT * FROM dbo.DANGNHAP WHERE TaiKhoan = @Username AND MatKhau = @Pass
END
GO

--  Proc phần Phiếu Nhập Kho
CREATE PROC ThemPhieuNhap( @SOPHIEU  varchar(8), @NGAYLAP datetime, @MAKHO  varchar(8)) AS
BEGIN
	INSERT INTO dbo.PHIEUNHAP( SOPHIEU, NGAYLAP, MAKHO )
	VALUES  ( @SOPHIEU, @NGAYLAP, @MAKHO )
END
GO
CREATE PROC SuaPhieuNhap( @SOPHIEU  varchar(8), @NGAYLAP datetime, @MAKHO  varchar(8)) AS
BEGIN
	UPDATE dbo.PHIEUNHAP
	 SET NGAYLAP = @NGAYLAP ,MAKHO = @MAKHO WHERE SOPHIEU = @SOPHIEU
END
GO
CREATE PROC XoaPhieuNhap( @SOPHIEU  varchar(8)) AS
BEGIN
	 DELETE FROM dbo.PHIEUNHAP WHERE SOPHIEU = @SOPHIEU
END
GO
--Proc KHO
CREATE PROCEDURE ADD_KHO(@MAKHO VARCHAR(8),@TENKHO NVARCHAR(100))
AS
BEGIN
		INSERT INTO KHO
		VALUES(@MAKHO,@TENKHO)
END
GO
--SỬA
CREATE PROCEDURE ALTER_KHO(@MAKHO VARCHAR(8),@TENKHO NVARCHAR(100))
AS
BEGIN
	UPDATE KHO
	SET MAKHO=@MAKHO,TENKHO=@TENKHO
	WHERE MAKHO=@MAKHO
			
END	
GO	
--XÓA
CREATE PROCEDURE D_KHO(@MAKHO VARCHAR(8))
AS
BEGIN 
	DELETE FROM KHO
	WHERE MAKHO=@MAKHO
END		
GO
--Vat Tu
INSERT INTO VATTU VALUES (N'VT01',N'Cột Sắt',N'Hải Phòng')
INSERT INTO VATTU VALUES (N'VT02',N'Xi Măng',N'Hải Phòng')
INSERT INTO VATTU VALUES (N'VT03',N'Cát',N'Hà Nội')
GO
CREATE PROCEDURE ThemVT(@MAVT VARCHAR(8),@TENVT NVARCHAR(100),@XUATXU NVARCHAR(100))
AS
BEGIN
		INSERT INTO VATTU
		VALUES(@MAVT,@TENVT,@XUATXU)
END
GO
CREATE PROCEDURE SuaVT(@MAVT VARCHAR(8),@TENVT NVARCHAR(100),@XUATXU NVARCHAR(100))
AS
BEGIN
	UPDATE VATTU
	SET MAVT=@MAVT,TENVT=@TENVT,XUATXU=@XUATXU
	WHERE MAVT=@MAVT
			
END	
GO	
CREATE PROCEDURE XoaVT(@MAVT VARCHAR(8))
AS
BEGIN 
	DELETE FROM VATTU
	WHERE MAVT=@MAVT
END		
GO