CREATE DATABASE quanlykho
GO
USE quanlykho
GO

CREATE TABLE KHO
(
	MAKHO VARCHAR(8) PRIMARY KEY,
	TENKHO NVARCHAR(100)
)
GO
CREATE TABLE PHIEUNHAP
(
	SOPHIEU VARCHAR(8) PRIMARY KEY,
	NGAYLAP DATETIME,
	MAKHO VARCHAR(8) REFERENCES KHO(MAKHO) ON DELETE CASCADE
)
GO
CREATE TABLE VATTU
(
	MAVT VARCHAR(8) PRIMARY KEY,
	TENVT NVARCHAR(100),
	XUATXU NVARCHAR(100)
)
GO
CREATE TABLE CHITIETPHIEUNHAP
(
	SOPHIEU VARCHAR(8) REFERENCES PHIEUNHAP(SOPHIEU) ON DELETE CASCADE,
	MAVT VARCHAR(8) REFERENCES VATTU(MAVT) ON DELETE CASCADE,
	PRIMARY KEY(MAVT,SOPHIEU),
	DONVITINH NVARCHAR(15),
	SOLUONG INT
)
GO
CREATE TABLE PHIEUXUAT
(
	MAPHIEU VARCHAR(8) PRIMARY KEY,
	NGAYXUAT DATE,
	MAKHO VARCHAR(8) REFERENCES KHO(MAKHO) ON DELETE CASCADE
)
GO
CREATE TABLE CHITIETPHIEUXUAT
(
	MAPHIEU VARCHAR(8) REFERENCES PHIEUXUAT(MAPHIEU) ON DELETE CASCADE,
	MAVT VARCHAR(8) REFERENCES VATTU(MAVT) ON DELETE CASCADE,
	PRIMARY KEY(MAVT,MAPHIEU),
	DONVITINH NVARCHAR(15),
	SOLUONG INT
)
GO
CREATE TABLE DANGNHAP
(
	TaiKhoan NVARCHAR(30),
	MatKhau VARCHAR(30)
)
GO
INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
VALUES  ( N'admin','123456'),
		( N'user1','123456')
GO
--Proc Dang Nhap
CREATE PROC DangKy(@Taikhoan NVARCHAR(30),@Matkhau NVARCHAR(30))
AS
	BEGIN
	INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
	VALUES  ( @Taikhoan, @Matkhau )
END
GO

CREATE PROC dbo.KiemTraDN(@Username VARCHAR(50),@Pass varchar(50)) AS 
BEGIN
	SELECT * FROM dbo.DANGNHAP WHERE TaiKhoan = @Username AND MatKhau = @Pass
END
GO

--  Proc phần Phiếu Nhập Kho
CREATE PROC ThemPhieuNhap( @SOPHIEU  varchar(8), @NGAYLAP datetime, @MAKHO  varchar(8)) AS
BEGIN
	INSERT INTO dbo.PHIEUNHAP( SOPHIEU, NGAYLAP, MAKHO )
	VALUES  ( @SOPHIEU, @NGAYLAP, @MAKHO )
END

CREATE PROC SuaPhieuNhap( @SOPHIEU  varchar(8), @NGAYLAP datetime, @MAKHO  varchar(8)) AS
BEGIN
	UPDATE dbo.PHIEUNHAP
	 SET NGAYLAP = @NGAYLAP ,MAKHO = @MAKHO WHERE SOPHIEU = @SOPHIEU
END

CREATE PROC XoaPhieuNhap( @SOPHIEU  varchar(8)) AS
BEGIN
	 DELETE FROM dbo.PHIEUNHAP WHERE SOPHIEU = @SOPHIEU
END